### ISSUE TITLE
Cache-Control header not set in Rails 5

### ISSUE THREAD

**Issue by crispwake** [romanbsd/heroku-deflater#39] opened 2017-05-19 15:28 UTC
I'm having trouble overwriting the Cache-Control header in my Rails 5 app.  I have the following in my `/config/environments/production.rb` file:

```
  config.public_file_server.headers = {
      'Cache-Control' => 'public, max-age=31536000',
      'Expires' => "#{1.year.from_now.to_formatted_s (:rfc822)}"
  }
```

This is applying to binary images fine (JPG/PNG/GIF) but JS and CSS assets still have the default max age of 86400 being applied (`public, max-age=86400`)

How am I able to update that?  Is the configuration setting above not supposed to apply to those files as well?

I've tried specifying the gem using the GIT url directly as I noticed a fix for this recently.  This did not change anything.  

When I enable them gem in development I see `max-age=31536000` set, however I don't seem to be able to update that either if I try a different value in `development.rb` and clear caches and restart servers.

**Comment by benoitongit** [comment] 2017-05-25 22:34
I have the same issue with Rails 5.1

**Comment by brian-kephart** [comment] 2017-06-07 17:35
There was a fix for this at the end of April, but a new release wasn't made. Are you two downloading the gem straight from this repository?

**Comment by romanbsd** [comment] 2017-06-08 07:11
If the git version fixes this issue, I'll go ahead and release an update.

**Comment by brian-kephart** [comment] 2017-06-09 00:54
I think it's still not fixed. I thought it was, because the header is correct when I request a file with `curl -I --compressed`. However, loading that same file in Chrome gets me the incorrect header that people have reported.

I just tried the fork from PR #40 by @bookwitty and it has problems as well. The header is set as a hash. In other words, this line:
`{ 'Cache-Control' => app.config.public_file_server.headers }`

results in this header:
`Cache-Control:{"Cache-Control"=>"public, max-age=31536000"}`

**Comment by benoitongit** [comment] 2017-06-09 11:43
15 days ago I tried from the repo and the released version but had no success. Cache control was always stuck to 24 hours.

**Comment by bmclean** [comment] 2017-06-15 14:23
@benoitongit Try adding this in config/initializers/heroku_deflater_patch.rb:
```ruby
module HerokuDeflater
  class CacheControlManager
    def cache_control_headers
      if rails_version_5?
        app.config.public_file_server.headers
      else
        app.config.static_cache_control
      end
    end
  end
end
```

**Closed** 2017-10-16 11:33 UTC

**Comment by oleksandrkits** [comment] 2018-10-29 10:04
@romanbsd can you please update it on Rubygems?

**Comment by justisb** [comment] 2019-09-26 19:58
Seems like this still never actually made it into a release?

**Comment by jmkristofzski** [comment] 2019-12-15 06:48
Rubygems version hasn't been updated since January 2017 (version 0.6.3).

Use the following to use the github version:
gem 'heroku-deflater', git: 'https://github.com/romanbsd/heroku-deflater'

**Comment by romanbsd** [comment] 2019-12-17 12:27
The issue is that commit f4d5b4cc2440027fd8bd7b279768d0f6ff344fdb while fixing one thing, broke another, and also the specs are failing. I hadn't had time to look into it, and then forgot about it completely. If someone is willing to check, I'll be more than happy to receive a PR and release a new version.
